apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
  labels:
    app: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      strategy:
        type: Recreate
      volumes:
      - name: conf
        configMap:
          name: squid-conf
      hostNetwork: true
      containers:
      - name: squid
        image: sameersbn/squid:3.5.27-2
        ports:
        - containerPort: 3128
        securityContext: 
          privileged: true
        volumeMounts:
        - name: conf
          mountPath: /etc/squid/squid.conf
          subPath: squid.conf
      nodeSelector:
        squid-proxy: ""

